name:                hscim
version:             0.3.0
synopsis:            ...
description:         ...
homepage:            https://github.com/wireapp/hscim/README.md
license:             AGPL-3
license-file:        LICENSE
author:              Wire Swiss GmbH
maintainer:          Wire Swiss GmbH <backend@wire.com>
copyright:           (c) 2018 Wire Swiss GmbH
category:            Web
build-type:          Simple
github:              wireapp/hscim

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances

extra-source-files:
  - README.md

dependencies:
  - aeson
  - aeson-qq
  - attoparsec
  - base >= 4.11 && < 5
  - bytestring
  - email-validate
  - errors
  - hashable
  - hedgehog
  - hspec
  - hspec-expectations
  - hspec-wai < 0.10
  - http-api-data
  - http-media
  - http-types
  - hw-hspec-hedgehog
  - list-t
  - microlens
  - mmorph
  - mtl
  - network-uri
  - network-uri-static >= 0.1.1.0
  - scientific
  - servant
  - servant-server >= 0.16 && < 0.17
  - stm
  - stm-containers
  - template-haskell
  - text
  - time
  - unordered-containers
  - uuid
  - vector
  - wai
  - wai-extra
  - wai-logger
  - warp

ghc-options: -Wall -Werror

library:
  source-dirs: src

executables:
  hscim-server:
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    source-dirs: server
    dependencies:
      - hscim

tests:
  spec:
    main: Spec.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    source-dirs:
      - test
    build-tools:
      - hspec-discover:hspec-discover
    dependencies:
      - hscim
