name:                hscim
version:             0.1.0.0
synopsis:            ...
description:         ...
homepage:            https://github.com/wireapp/hscim/README.md
license:             AGPL-3
license-file:        LICENSE
author:              Wire Swiss GmbH
maintainer:          Wire Swiss GmbH <backend@wire.com>
copyright:           (c) 2018 Wire Swiss GmbH
category:            Web
build-type:          Simple
github:              wireapp/hscim

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - base64-bytestring
  - aeson
  - aeson-qq
  - mtl
  - servant
  - servant-server
  - servant-generic
  - text
  - time
  - wai
  - network-uri
  - network-uri-static >= 0.1.1.0
  - unordered-containers
  - email-validate
  - errors
  - stm
  - list-t
  - http-types
  - stm-containers
  - http-media
  - uuid
  - template-haskell
  - scientific
  - attoparsec
  - microlens
  - http-api-data
  - mmorph
  - QuickCheck
  - hedgehog
  - hedgehog-quickcheck

ghc-options: -Wall

library:
  source-dirs: src

executables:
  hscim-server:
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    source-dirs: server
    dependencies:
      - hscim
      - warp

tests:
  spec:
    main: Spec.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    source-dirs:
      - test
      - src
    dependencies:
      - base
      - bytestring
      - hscim
      - hspec
      - hspec-wai
      - aeson
      - aeson-qq
      - http-types
      - text
      - bytestring
      - wai-extra
      - stm-containers
      - mtl
      - time
      - servant-server
      - vector
      - hspec-expectations
      - hspec-discover
      - warp
      - template-haskell
      - aeson-qq
      - wai-logger
      - base64-bytestring
      - hedgehog
      - hw-hspec-hedgehog
      - servant-swagger == 1.1.4.*
      - QuickCheck
      - swagger2
